version: '3'
services:
  
  backend:
    build: "./bin/backend"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./backend:/home/node/app
    ports:
      - "9000:3000"
    command: "npm start"

  database:
    image: "mysql:5.6"
    volumes:
      - "./database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
